# version: '1.1'

services:
  sneakers-next:
    container_name: sneakers-next
    restart: always
    image: node:20.9.0
    ports:
      - 4000:3000
    environment:
      - PORT=3000
    volumes:
      - ./:/usr/src/sneakers-next
    working_dir: /usr/src/sneakers-next

    networks:
      - client-network

    # FOR PRODUCTION
    command: bash -c "yarn && yarn run build && yarn run start"

networks:
  client-network:
    driver: bridge
# sneakers-next:  localhost:4000 => container:3000
# sneakers-api:   localhost:4001 => container:3007
# sneakers-batch: localhost:4002 => container:3008
